Repository fightmegg/riot-rate-limiter, pull requests merged in 2021-07, with the labels that each got.

#250 fix the reservoir limit
  __tests__/unit/rate-limiter.test.ts
  src/rate-limiter.ts
Labels: bug

#259 feat(matchv5): MatchV5 Endpoints
  __tests__/unit/extractor.test.ts
  src/@types/index.ts
Labels: enhancement

#260 chore(deps): Updated dependencies + dependabot is now weekly
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: dependencies
